---
name: rubyapp

blobstore:
  provider: local
  options:
    blobstore_path: /tmp/ruby-blobs


# blobstore:
#   provider: s3
#   options:
#     bucket_name: a9s-blobs
#     endpoint: https://s3-eu-west-1.amazonaws.com
#     region: eu-west-1
